package:
  name: libclock_gettime_wrapper
  version: 2.17

source:
  - path: ./

build:
  number: 2
  string: {{ PKG_BUILDNUM }}
  
requirements:
  build:
    - {{ compiler('c') }}

about:
  home: open-ce
  license: LGPL
  license_family: LGPL
  license_file: LICENSE
  summary: wrapper for clock_gettime version compatibility
  description: |
    This is a wrapper package to map clock_gettime_GLIBC_PRIVATE to GLIBC_2.17
  doc_url: 

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
