package:
  name: libmemcpy_wrapper
  version: 2.14

source:
  - path: ./

build:
  number: 2
  string: {{ PKG_BUILDNUM }}
  
requirements:
  build:
    - {{ compiler('c') }}

about:
  home: open-ce
  license: apache-2
  license_family: APACHE  
  license_file: LICENSE
  summary: wrapper for memcpy version compatibility
  description: |
    This is a wrapper package to map memcpy_GLIBC_2.2.5 to GLIBC_2.14
  doc_url: 

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
