recipes:
  - name : libclock_gettime_wrapper    #[x86_64]
    path : libclock_gettime_wrapper    #[x86_64]

  - name : libmemcpy_wrapper           #[x86_64]
    path : libmemcpy_wrapper           #[x86_64]
